# Euro Data Cube - geoDB: Getting Started (13)

The Euro Data Cube Jupyter Lab environment has all dependencies preinstalled and the necessary credentials prepared as environment variables.

To run this notebook outside of this environment please follow the setup outlined [here](././99_EDC_Setup.ipynb).

## Sharing Data

This notebook shows how to grant and revoke public access to a collection stored in geoDB.

In [1]:
from xcube_geodb.core.geodb import GeoDBClient

In [2]:
geodb = GeoDBClient()
geodb.whoami

'geodb_test99'

### Publish Dataset to the world

In [3]:
geodb.grant_access_to_collection("land_use", 'public')

Access granted on land_use to public

In [4]:
geodb = GeoDBClient(anonymous=True)
geodb.whoami

'publicaccess'

In [5]:
gdf = geodb.get_collection_by_bbox(collection="land_use", bbox=(452750.0, 464000.0, 88909.549, 102486.299),
                           comparison_mode="contains", bbox_crs=3794, limit=200, offset=10, namespace='geodb_admin')
gdf

,created_at,d_od,geometry,id,modified_at,raba_id,raba_pid
0,2020-02-04T12:05:57.936447+00:00,2019-03-26,"POLYGON ((453673.609 91328.224, 453678.929 913...",12,None,1600,5983074
1,2020-02-04T12:05:57.936447+00:00,2019-03-11,"POLYGON ((460312.295 96127.114, 460300.319 961...",13,None,1600,5983199
2,2020-02-04T12:05:57.936447+00:00,2019-03-11,"POLYGON ((460459.445 96117.356, 460470.516 961...",14,None,1100,5983217
3,2020-02-04T12:05:57.936447+00:00,2019-03-04,"POLYGON ((457798.753 99628.982, 457783.076 996...",15,None,1600,6299143
4,2020-02-04T12:05:57.936447+00:00,2019-02-21,"POLYGON ((461439.703 92137.401, 461436.166 921...",16,None,1600,4643632
5,2020-02-04T12:05:57.936447+00:00,2019-03-08,"POLYGON ((460620.185 96237.242, 460629.648 962...",17,None,1100,5983326
6,2020-02-04T12:05:57.936447+00:00,2019-03-11,"POLYGON ((461039.853 96009.448, 461052.662 959...",18,None,1500,5983364
7,2020-02-04T12:05:57.936447+00:00,2019-03-04,"POLYGON ((459432.100 99387.685, 459437.526 993...",19,None,3000,4682742
8,2020-02-04T12:05:57.936447+00:00,2019-02-25,"POLYGON ((455215.954 98423.695, 455219.643 984...",20,None,1321,2304135
9,2020-02-04T12:05:57.936447+00:00,2019-03-13,"POLYGON ((456552.015 93234.565, 456513.830 931...",21,None,1100,2311433
10,2020-02-04T12:05:57.936447+00:00,2019-02-25,"POLYGON ((455384.809 97907.054, 455380.659 979...",22,None,1410,3616776
11,2020-02-04T12:05:57.936447+00:00,2019-03-20,"POLYGON ((463208.897 96053.637, 463196.955 960...",23,None,3000,2316136
12,2020-02-04T12:05:57.936447+00:00,2019-03-20,"POLYGON ((462452.425 96822.124, 462450.309 968...",24,None,1100,2309910
13,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((457190.207 90846.037, 457190.207 908...",25,None,3000,2308922
14,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((457124.020 90792.907, 457124.197 908...",27,None,3000,2308735
15,2020-02-04T12:05:57.936447+00:00,2019-01-23,"POLYGON ((462585.734 93088.987, 462567.020 930...",28,None,1410,3826126
16,2020-02-04T12:05:57.936447+00:00,2019-01-23,"POLYGON ((462168.988 93752.914, 462169.682 937...",29,None,1500,3826129
17,2020-02-04T12:05:57.936447+00:00,2019-04-09,"POLYGON ((456878.975 98493.225, 456885.718 984...",30,None,1500,2306936
18,2020-02-04T12:05:57.936447+00:00,2019-02-26,"POLYGON ((456707.537 98648.869, 456667.431 987...",31,None,1100,2307044
19,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((457748.827 96167.354, 457748.394 961...",32,None,1410,2309744
20,2020-02-04T12:05:57.936447+00:00,2019-03-26,"POLYGON ((455176.193 94096.030, 455153.180 940...",33,None,1321,2307091
21,2020-02-04T12:05:57.936447+00:00,2019-04-01,"POLYGON ((456405.039 100087.946, 456399.544 10...",34,None,1410,2302127
22,2020-02-04T12:05:57.936447+00:00,2019-03-26,"POLYGON ((456124.289 94046.233, 456147.848 940...",35,None,1100,2312110
23,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((456878.933 96446.382, 456878.933 964...",36,None,1500,3596318
24,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((456878.934 96527.529, 456878.934 965...",37,None,1500,3596316
25,2020-02-04T12:05:57.936447+00:00,2019-03-11,"POLYGON ((460984.536 94798.368, 460983.159 947...",38,None,1321,5983583
26,2020-02-04T12:05:57.936447+00:00,2019-03-11,"POLYGON ((461072.645 94790.639, 460984.536 947...",39,None,1100,5983579
27,2020-02-04T12:05:57.936447+00:00,2019-03-11,"POLYGON ((460834.057 96388.063, 460843.175 963...",40,None,1100,5983370
28,2020-02-04T12:05:57.936447+00:00,2019-03-11,"POLYGON ((460961.168 96451.823, 460967.256 964...",41,None,1100,5983378
29,2020-02-04T12:05:57.936447+00:00,2019-03-11,"POLYGON ((461210.843 95124.328, 461204.874 951...",42,None,1600,5983414
...,...,...,...,...,...,...,...
170,2020-02-04T12:05:57.936447+00:00,2019-02-21,"POLYGON ((459866.862 91774.423, 459863.171 917...",190,None,1222,2332890
171,2020-02-04T12:05:57.936447+00:00,2000-01-01,"POLYGON ((454435.798 91016.834, 454445.707 910...",191,2020-02-04T12:06:01.985734+00:00,1300,6097356
172,2020-02-04T12:05:57.936447+00:00,2000-01-01,"POLYGON ((454448.966 90832.226, 454455.922 908...",192,2020-02-04T12:06:01.985734+00:00,1300,6097360
173,2020-02-04T12:05:57.936447+00:00,2019-03-07,"POLYGON ((453856.057 100395.407, 453861.036 10...",193,None,3000,2356795
174,2020-02-04T12:05:57.936447+00:00,2019-02-26,"POLYGON ((456113.390 99078.867, 456104.124 990...",194,None,1600,6294777
175,2020-02-04T12:05:57.936447+00:00,2000-01-01,"POLYGON ((454701.445 92825.227, 454697.793 928...",195,2020-02-04T12:06:01.985734+00:00,1300,5909727
176,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((459128.912 95236.688, 459119.740 952...",196,None,1500,3805619
177,2020-02-04T12:05:57.936447+00:00,2019-03-27,"POLYGON ((460415.468 97491.247, 460412.455 974...",197,None,1600,5183135
178,2020-02-04T12:05:57.936447+00:00,2019-03-27,"POLYGON ((460366.633 97486.434, 460367.511 974...",198,None,1600,5183143
179,2020-02-04T12:05:57.936447+00:00,2019-02-21,"POLYGON ((459608.148 92981.752, 459608.893 930...",199,None,1321,2493297
180,2020-02-04T12:05:57.936447+00:00,2019-03-08,"POLYGON ((461151.854 96728.105, 461142.587 967...",200,None,1100,2558688
181,2020-02-04T12:05:57.936447+00:00,2019-03-27,"POLYGON ((460275.167 97443.847, 460268.580 974...",201,None,1100,5791512
182,2020-02-04T12:05:57.936447+00:00,2019-03-27,"POLYGON ((460157.423 97347.374, 460152.541 973...",202,None,1410,5791522
183,2020-02-04T12:05:57.936447+00:00,2019-03-27,"POLYGON ((460193.303 97282.027, 460188.818 972...",203,None,1410,5791524
184,2020-02-04T12:05:57.936447+00:00,2019-03-11,"POLYGON ((460256.099 94636.034, 460254.624 946...",204,None,1410,4652943
185,2020-02-04T12:05:57.936447+00:00,2019-03-20,"POLYGON ((462034.451 95592.708, 462032.717 955...",205,None,1100,6088270
186,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((458460.702 94486.435, 458450.740 944...",206,None,1321,5966292
187,2020-02-04T12:05:57.936447+00:00,2019-03-26,"POLYGON ((458469.826 94472.438, 458463.978 944...",207,None,1500,5966293
188,2020-02-04T12:05:57.936447+00:00,2019-01-18,"POLYGON ((455171.131 90548.851, 455158.322 905...",208,None,1500,3590222
189,2020-02-04T12:05:57.936447+00:00,2019-03-14,"POLYGON ((456420.815 92626.252, 456428.630 926...",209,None,1500,6305200
190,2020-02-04T12:05:57.936447+00:00,2019-03-14,"POLYGON ((456437.664 92667.683, 456433.667 926...",210,None,1100,6305202
191,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((456878.908 95325.887, 456878.908 953...",211,None,1500,3805904
192,2020-02-04T12:05:57.936447+00:00,2019-02-25,"POLYGON ((456900.790 99320.185, 456897.968 993...",212,None,1600,5952609
193,2020-02-04T12:05:57.936447+00:00,2019-02-26,"POLYGON ((455221.048 99014.473, 455215.190 990...",213,None,1600,6294760
194,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((458606.182 95401.171, 458653.859 953...",214,None,1100,5966558
195,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((458934.146 95656.658, 458932.345 956...",215,None,1222,5966575
196,2020-02-04T12:05:57.936447+00:00,2019-01-05,"POLYGON ((458934.146 95656.658, 458935.525 956...",216,None,1100,5966577
197,2020-02-04T12:05:57.936447+00:00,2019-03-14,"POLYGON ((455301.879 91279.877, 455302.373 912...",217,None,1100,2594677
198,2020-02-04T12:05:57.936447+00:00,2019-03-14,"POLYGON ((455207.927 91222.221, 455193.596 912...",218,None,1100,2594678
199,2020-02-04T12:05:57.936447+00:00,2019-02-26,"POLYGON ((456955.636 98474.696, 456952.435 984...",219,None,1500,2960296

### Revoke access

In [6]:
geodb = GeoDBClient()
geodb.whoami

'geodb_test99'

In [7]:
geodb.list_grants()

[{'table_name': 'geodb_test99_land_use', 'grantee': 'PUBLIC'}]

In [8]:
geodb.revoke_access_from_collection("land_use")

Access revoked from land_use of public

In [9]:
geodb = GeoDBClient(anonymous=True)
geodb.whoami

'publicaccess'

In [10]:
gdf = geodb.get_collection_by_bbox(collection="land_use", bbox=(452750.0, 88909.549, 464000.0, 102486.299),
                comparison_mode="contains", bbox_crs=3794, limit=2, offset=10, namespace='geodb_admin')
gdf

ValueError: Collection geodb_admin_land_use does not exist